import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle2, FileText, Loader2, Bot } from "lucide-react";
import { PageHeader, Panel, SeverityBadge } from "@/components/astro/primitives";
import { SendReportDialog } from "@/components/astro/dialogs";
import { useAstro } from "@/lib/astro/store";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Mission Health Reports — AstroGalen" },
      { name: "description", content: "Review, generate and transmit astronaut health reports to Mission Control." },
      { property: "og:title", content: "Mission Health Reports — AstroGalen" },
      { property: "og:description", content: "Review and transmit health summaries to Mission Control." },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const { state } = useAstro();
  const [selected, setSelected] = useState<string | null>(null);
  const r = state.reports.find((x) => x.id === selected) ?? state.reports[0];
  const worst = (rep: typeof r) => rep.risks[0];

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Communications" title="Mission Health Reports" subtitle="Review and transmit health summaries to Mission Control." actions={<SendReportDialog />} />
      <div className="grid gap-4 xl:grid-cols-[420px_1fr]">
        <Panel eyebrow={`${state.reports.length} reports`} title="Report history">
          <ul className="space-y-2">
            {state.reports.map((rep) => (
              <li key={rep.id}>
                <button onClick={() => setSelected(rep.id)} className={cn("w-full rounded-lg border p-3 text-left transition-colors", rep.id === r.id ? "border-primary bg-accent" : "bg-card hover:bg-surface-2")}>
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-sm font-semibold text-foreground">#{rep.id}</span>
                    {rep.transmissionStatus === "Sent" ? (
                      <span className="inline-flex items-center gap-1 text-xs font-semibold text-success"><CheckCircle2 className="h-3.5 w-3.5" /> Sent</span>
                    ) : (
                      <span className="inline-flex items-center gap-1 text-xs font-semibold text-info"><Loader2 className="h-3.5 w-3.5 animate-spin" /> Transmitting</span>
                    )}
                  </div>
                  <div className="mt-1 text-xs text-muted-foreground">{rep.createdAt}{rep.auto ? " · Automatic" : " · Manual"}</div>
                  <div className="mt-2 flex items-center gap-2"><SeverityBadge severity={worst(rep).severity} /><span className="truncate text-sm text-foreground">{worst(rep).title}</span></div>
                </button>
              </li>
            ))}
          </ul>
        </Panel>

        <section className="panel p-6">
          <div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4">
            <div>
              <div className="eyebrow flex items-center gap-1.5"><FileText className="h-3.5 w-3.5" /> AstroGalen Health Report</div>
              <h2 className="mt-1 font-mono text-2xl font-semibold text-foreground">#{r.id}</h2>
              <div className="mt-1 text-sm text-muted-foreground">Mission Day {r.missionDay} · {r.createdAt.split("· ")[1]} · Crew {r.crewId}</div>
            </div>
            <div className="text-right">
              <div className="eyebrow">Wellness score</div>
              <div className="font-display text-3xl font-semibold text-foreground tabular">{r.score}</div>
            </div>
          </div>
          {r.auto && <div className="mt-4 flex items-center gap-2 rounded-lg border border-high/30 bg-high/10 px-3 py-2 text-sm font-semibold text-high"><Bot className="h-4 w-4" /> Automatically generated by the risk engine{r.eventId ? ` · event ${r.eventId}` : ""}</div>}
          <div className="mt-5 grid gap-6 lg:grid-cols-2">
            <div>
              <div className="eyebrow mb-2">Current vitals</div>
              <dl className="divide-y rounded-lg border">
                {r.metrics.map((m) => <div key={m.label} className="flex justify-between px-3 py-2 text-sm"><dt className="text-muted-foreground">{m.label}</dt><dd className="font-semibold text-foreground tabular">{m.value}</dd></div>)}
              </dl>
              <div className="eyebrow mt-4 mb-1">Sensor status</div>
              <div className="text-sm text-foreground">{r.sensorSummary}</div>
            </div>
            <div className="space-y-4">
              {r.risks.map((rk) => (
                <div key={rk.title}>
                  <div className="eyebrow mb-1">Detected risk</div>
                  <div className="flex items-center gap-2"><span className="font-display text-lg font-semibold text-foreground">{rk.title}</span><SeverityBadge severity={rk.severity} /></div>
                  <div className="eyebrow mt-2 mb-1">Evidence</div>
                  <ul className="space-y-0.5 text-sm text-muted-foreground">{rk.evidence.map((e) => <li key={e}>• {e}</li>)}</ul>
                </div>
              ))}
              <div>
                <div className="eyebrow mb-1">Recommended next action</div>
                <ul className="space-y-1 text-sm text-foreground">{[...new Set(r.recommendations)].map((x) => <li key={x}>→ {x}</li>)}</ul>
              </div>
              <div>
                <div className="eyebrow mb-1">Transmission status</div>
                <div className={cn("text-sm font-semibold", r.transmissionStatus === "Sent" ? "text-success" : "text-info")}>{r.transmissionStatus === "Sent" ? "✓ Delivered to Mission Control (simulated)" : "Transmitting…"}</div>
              </div>
            </div>
          </div>
          <p className="mt-6 text-xs text-muted-foreground">Prototype report. Does not diagnose medical conditions or replace mission medical procedures.</p>
        </section>
      </div>
    </div>
  );
}
